# Generated by Django 4.2.2 on 2023-06-19 15:00

import authenticacao.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticacao', '0003_alter_users_password'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', authenticacao.models.UserManager()),
            ],
        ),
    ]
