# Generated by Django 4.2.2 on 2023-06-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgets',
            name='file_path',
            field=models.CharField(max_length=300),
        ),
    ]
